# roles/httpd/tasks/main.yml
---

- name: install the Apache rpm from a remote repo
  yum:
    name: http://apache.mirror.triple-it.nl//directory/apacheds/dist/2.0.0.AM26/apacheds-2.0.0.AM26-x86_64.rpm
    state: present
  when: action == "install"

- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
  when: action == "upgrade"

- name: install a specific version of httpd is installed
  yum:
    name: "{{ package_version }}"
    state: present
  when: action == "downgrade"

- name: Ensure Apache is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"
 

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  

- name: Install status configuration file
  template:
    src: etc_httpd_conf.d_status.conf.j2
    dest: "{{ httpd_status_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  when: httpd_status_enable

- name: Ensure Apache is always running
  service:
    name: httpd
    state: started
    enabled: true
